# Generated by Django 5.2.7 on 2025-10-07 05:33

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_colors_sizes_product_count_product_colors_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
