# Generated by Django 5.2.7 on 2025-10-07 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_materials_producer_product_guarantee_product_lengths_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='colors',
            name='code',
            field=models.CharField(max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='colors',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
