# Generated by Django 5.2.7 on 2025-10-09 07:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_productview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productview',
            name='rate',
            field=models.IntegerField(default=0, help_text='1 dan 5 gacha yulduz bering', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
